name: Reusable workflow two

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.example_job.outputs.output1 }}
      secondword:
        description: "The second output string"
        value: ${{ jobs.example_job.outputs.output2 }}

jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.step1.outputs.firstname }}
      output2: ${{ steps.step2.outputs.lastname }}
    steps:
      - id: step1
        run: echo "::set-output name=firstname::Swati"
      - id: step2
        run: echo "::set-output name=lastname::Gupta"
