name: demo of reusing a workflow

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
   inputs:
      name:
        type: string
        required: true
      age:
        type: string
        required: true
      company:
        type: string
        required: true

jobs:
  myjob1:
    name: Input Details
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      name: ${{ steps.step1.outputs.name }}
      age: ${{ steps.step2.outputs.age }}
      company: ${{ steps.step2.outputs.company}}
    steps:
    - id: step1
      run: echo "name=${{inputs.name}}" >> $GITHUB_OUTPUT
    - id: step2
      run: echo "age=${{inputs.age}}" >> $GITHUB_OUTPUT
    - id: step3
      run: echo "company=${{inputs.company}}" >> $GITHUB_OUTPUT
  myjob2:
    name: Is it Madhavi
    runs-on: ubuntu-latest
    needs: myjob1
    if: needs.myjob1.outputs.name == 'madhavi'
    steps:
    - run: echo ${{needs.myjob1.outputs.name}} ${{needs.myjob1.outputs.age}}
  
  myjob3: 
    name: If Madhavi skip this
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: myjob2
    steps:
    - run: echo myjob2 is skipped 
    
 # Uses reuseme.yml       
  call-reusable-workflow-1:
    name: Reuseme called M
    needs: myjob2
    uses: madhavirkl84/AutomationPractice/.github/workflows/reuseme.yml@main
    with:
      name: Madhavi
      company: Software AG
     
  call-reusable-workflow-2:
    name: Reuseme called GM 
    needs: myjob1
    uses: madhavirkl84/AutomationPractice/.github/workflows/reuseme.yml@main
    with:
      name: ggm
      company: SoftwareAG Intern
      
  # Uses Reuse2.yml      
  job3:
    uses: madhavirkl84/AutomationPractice/.github/workflows/Reuse2.yml@main
    needs: myjob1 
    # if: needs.myjob1.outputs.name == 'Swati'
     # echo Hi Swati!!
  job4:
    runs-on: ubuntu-latest
    needs: job3
    steps:
        - run: echo ${{needs.job3.outputs.firstword}} ${{needs.job3.outputs.secondword}}
        - run: echo "$QM"
    env:
      QM : ${{secrets.SECRET_TOKEN}}     
