name: demo of reusing a workflow

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
   inputs:
      name:
        type: string
        required: true
      age:
        type: string
        required: true

jobs:
  job3:
    uses: madhavirkl84/AutomationPractice/.github/workflows/Reuse2.yml@main
  job4:
    runs-on: ubuntu-latest
    needs: job3
    name: testing secret
    steps:
         - run: echo ${{needs.job3.outputs.firstword}} ${{needs.job3.outputs.secondword}}
         - run: echo "$QM"
    env:
      QM : ${{secrets.SECRET_TOKEN}}
      
  myjob1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      name: ${{ steps.step1.outputs.name }}
      age: ${{ steps.step2.outputs.age }}
    steps:
    - id: step1
      run: echo ${{inputs.name}} >> $GITHUB_OUTPUT
    - id: step2
      run: echo ${{inputs.age}} >> $GITHUB_OUTPUT
  myjob2:
    runs-on: ubuntu-latest
    needs: myjob1
    if: needs.myjob1.outputs.name == 'madhavi'
    steps:
    - run: echo ${{needs.myjob1.outputs.name}} ${{needs.myjob1.outputs.age}}
  
  myjob3:
    runs-on: ubuntu-latest
    needs: myjob2
    if: needs.myjob2.result == 'skipped'
    steps:
      - run: echo myjob2 is skipped 
    
          
  call-reusable-workflow-1:
    uses: madhavirkl84/AutomationPractice/.github/workflows/reuseme.yml@main
    with:
      name: ${{inputs.name}}
      company: SoftwareAG
     
  call-reusable-workflow-2:
    needs: [call-reusable-workflow-1]
    uses: madhavirkl84/AutomationPractice/.github/workflows/reuseme.yml@main
    with:
      name: ggm
      company: SoftwareAG Intern
      
